import type { AppProps } from "next/app";
import { Sen } from "next/font/google";
import Head from "next/head";

const sen = Sen({
  subsets: ['latin'],
  weight: ["400", "700"],
})

export default function App({ Component, pageProps }: AppProps) {
  return(
    <main className={sen.className}>
      <Head>
        <title>FFOHQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </main>
  )
}
